"""Purpose: Frontend namespace configuration.

Usage: Defines cfg with language labels, aura labels, and constants.

Functions available:
- None

Classes available:
- cfg

Call hierarchy:
- name_space.py -> frontend.i18n
"""

class cfg:
    DEFAULT_LANGUAGE = "de"
    LANGUAGE_LABELS = {"de": "Deutsch", "en": "English"}
    AURA_LABELS = {
    "F": ("Flimmersehen", "Flickering vision"),
    "G": ("Gefühlsstörung (Kribbeln, Pelzigkeit)", "Sensory disturbance (tingling, numbness)"),
    "S": ("Sprachstörung", "Speech disturbance"),
    "O": ("Anderes Symptom", "Other symptom"),
    "*": ("Noch ein anderes Symptom", "Another symptom"),
    }

    OTHER_SYMPTOM_LABELS = {
    "T": ("Augentränen", "Watery eyes"),
    "R": ("Augenrötung", "Eye redness"),
    "N": ("Nasenlaufen / -verstopfung", "Runny / blocked nose"),
    }

    DERIVED_LATERALITY_LABELS = {
    "unbekannt": ("Unbekannt", "Unknown"),
    "rechts": ("Rechts", "Right"),
    "links": ("Links", "Left"),
    "beidseitig": ("Beidseitig", "Bilateral"),
    "beidseitig_linksbetont": ("Beidseitig, linksbetont", "Bilateral, left-dominant"),
    "einseitig_unbekannt": ("Einseitig, Seite offen", "Unilateral, side unclear"),
    }

    CODE_LABELS = {
    "daily_only": ("Beobachtungstag ohne Kopfschmerz", "Observation day without headache"),
    "imported": ("Importiert", "Imported"),
    "updated": ("Aktualisiert", "Updated"),
    "skipped": ("Übersprungen", "Skipped"),
    "duplicate": ("Duplikat", "Duplicate"),
    "rejected": ("Abgelehnt", "Rejected"),
    "created": ("Erstellt", "Created"),
    "excel_migration": ("Historischer Bestand", "Historical legacy record"),
    "ai_assisted": ("KI-gestützter Eintrag", "AI-assisted entry"),
    "unbekannt": ("Unbekannt", "Unknown"),
    "rechts": ("Rechts", "Right"),
    "links": ("Links", "Left"),
    "beidseitig_linksbetont": ("Beidseitig, linksbetont", "Bilateral, left-dominant"),
    "einseitig_unbekannt": ("Einseitig, Seite offen", "Unilateral, side unclear"),
    }

    TRIGGER_LABELS_EN = {
    "1": "Excitement / stress",
    "2": "Recovery phase",
    "3": "Change in sleep-wake rhythm",
    "4": "Menstruation",
    "5": "Cold sleeping environment / open window",
    "6": "Heat / high outdoor temperature",
    "7": "Late and insufficient sleep",
    "8": "Uncertain",
    "P1": "Personal trigger",
    "ND": "Not documented (legacy)",
    }

    TRIGGER_DESCRIPTIONS_EN = {
    "1": "DMKG trigger",
    "2": "DMKG trigger",
    "3": "DMKG trigger",
    "4": "DMKG trigger",
    "5": "Personal: approx. 17–18 °C",
    "6": "Personal: above 38 °C during the day",
    "7": "Personal trigger",
    "8": "Trigger cannot be assigned with certainty",
    "ND": "Only for legacy entries without a documented trigger.",
    }

    VALUE_TRANSLATIONS = {
    "Nicht dokumentiert": "Not documented",
    "Nicht dokumentiert (Altbestand)": "Not documented (legacy)",
    "Nicht ausgewählt": "Not selected",
    "Ja": "Yes",
    "Nein": "No",
    "Teilweise": "Partly",
    "Aktiv": "Active",
    "Inaktiv": "Inactive",
    "Dumpf / drückend": "Dull / pressing",
    "Pulsierend / stechend": "Throbbing / stabbing",
    "Einseitig": "Unilateral",
    "Beidseitig": "Bilateral",
    "Rechts": "Right",
    "Links": "Left",
    "Beidseitig, linksbetont": "Bilateral, left-dominant",
    "Einseitig, Seite offen": "Unilateral, side unclear",
    "beidseitig, links stärker": "bilateral, stronger on the left",
    "beidseitig": "bilateral",
    "rechtsseitig": "right-sided",
    "linksseitig": "left-sided",
    "rechts (aus Notiz abgeleitet)": "right (derived from note)",
    "links (aus Notiz abgeleitet)": "left (derived from note)",
    "einseitig, Seite nicht dokumentiert": "unilateral, side not documented",
    "Hinterkopf, später über beiden Augen": "back of the head, later above both eyes",
    "ausschließlich rechts": "right side only",
    "ausschließlich links": "left side only",
    "beidseitig, links etwas stärker": "bilateral, slightly stronger on the left",
    "links, im Bereich des linken Auges": "left, around the left eye",
    "links, über dem linken Auge": "left, above the left eye",
    "rechts, im Bereich des rechten Auges": "right, around the right eye",
    "Kälte / Zugluft": "Cold / draught",
    "Offenes Fenster": "Open window",
    "Später Schlaf / Schlafmangel": "Late sleep / sleep deprivation",
    "Unterbrochener Schlaf / Baby": "Interrupted sleep / baby",
    "Hitze / hohe Temperatur": "Heat / high temperature",
    "Möglicherweise zu wenig getrunken": "Possibly insufficient hydration",
    "Unterbrochener Schlaf / Unruhe": "Interrupted sleep / disturbance",
    "Übelkeit": "Nausea",
    "Erbrechen": "Vomiting",
    "Lärmscheu": "Sensitivity to sound",
    "Lichtscheu": "Sensitivity to light",
    "Geruchsempfindlichkeit": "Sensitivity to smell",
    "Schlaf": "Sleep",
    "Akutmedikation": "Acute medication",
    "Wärme": "Heat treatment",
    "Bad": "Bath",
    "Tigerbalsam": "Tiger balm",
    "niedrig": "low",
    "mittel": "medium",
    "hoch": "high",
    "regelbasiert": "rule-based",
    "semantisch geprüft": "semantically reviewed",
    "vollständig": "complete",
    "nahezu vollständig": "nearly complete",
    "letzte Dokumentation": "last documented time",
    "mindestens bis": "at least until",
    "vollständig oder nahezu vollständig": "complete or nearly complete",
    "dokumentiert": "documented",
    "Montag": "Monday",
    "Dienstag": "Tuesday",
    "Mittwoch": "Wednesday",
    "Donnerstag": "Thursday",
    "Freitag": "Friday",
    "Samstag": "Saturday",
    "Sonntag": "Sunday",
    "Nacht (00–05:59)": "Night (00:00–05:59)",
    "Morgen (06–11:59)": "Morning (06:00–11:59)",
    "Nachmittag (12–17:59)": "Afternoon (12:00–17:59)",
    "Abend (18–23:59)": "Evening (18:00–23:59)",
    "Vor Amitriptylin": "Before amitriptyline",
    "Amitriptylin dokumentiert": "Amitriptyline documented",
    "Nach Amitriptylin, vor Aimovig": "After amitriptyline, before Aimovig",
    "Seit erster Aimovig-Injektion": "Since first Aimovig injection",
    "Weitere Beobachtung": "Further observation",
    "Beobachtungsphase": "Observation period",
    "Keine kausale Wirksamkeitsaussage": "No causal efficacy conclusion",
    "Kurze Übergangsphase": "Short transition period",
    "Für eine Wirksamkeitsbewertung noch zu kurz": "Still too short for an efficacy assessment",
    "Beobachtungstag ohne Kopfschmerz": "Observation day without headache",
    "Kopfschmerzeintrag importiert": "Headache entry imported",
    "Beim erneuten Import aktualisiert": "Updated during repeated import",
    "Unverändert übersprungen": "Skipped unchanged",
    "Duplikat": "Duplicate",
    "Abgelehnt": "Rejected",
    "Aufregung / Stress": "Excitement / stress",
    "Erholungsphase": "Recovery phase",
    "Änderung im Schlaf-Wach-Rhythmus": "Change in sleep-wake rhythm",
    "Menstruation": "Menstruation",
    "Kalte Schlafumgebung / Fenster offen": "Cold sleeping environment / open window",
    "Hitze / hohe Außentemperatur": "Heat / high outdoor temperature",
    "Spät und zu wenig Schlaf": "Late and insufficient sleep",
    "Unsicher": "Uncertain",
    "DMKG-Auslöser": "DMKG trigger",
    "Persönlicher Auslöser": "Personal trigger",
    "Persönlich: ca. 17–18 °C": "Personal: approx. 17–18 °C",
    "Persönlich: >38 °C tagsüber": "Personal: above 38 °C during the day",
    "Auslöser nicht sicher zuordenbar": "Trigger cannot be assigned with certainty",
    "Nur für ältere Einträge ohne dokumentierten Auslöser.": "Only for legacy entries without a documented trigger.",
    "Kopfschmerzeinträge": "Headache entries",
    "Medikamenteneinnahmen": "Medication intakes",
    "Beobachtungstage": "Observation days",
    "Notizinterpretationen": "Note interpretations",
    "Auslöserzuordnungen": "Trigger assignments",
    "Änderungsprotokoll": "Change log",
    "Personen": "People",
    "Auslöserkatalog": "Trigger catalogue",
    "Automatisch ausgewertete Notizen": "Automatically analysed notes",
    "Ausgewählte Auslöser": "Selected triggers",
    "Verfügbare Auslöser": "Available triggers",
    "Dokumentierte Kopfschmerz- und Migränetage.": "Documented headache and migraine days.",
    "Alle einzelnen Medikamenteneinnahmen mit Uhrzeit, Dosis und dokumentierter Wirkung.": "All individual medication intakes with time, dose, and documented effect.",
    "Kalendertage und vorbeugende Behandlungen.": "Calendar days and preventive treatments.",
    "Aus den Originalnotizen abgeleitete und geprüfte Angaben.": "Information derived from and reviewed against the original notes.",
    "Den einzelnen Einträgen zugeordnete Auslöser.": "Triggers assigned to individual entries.",
    "Erstellungen und Änderungen an Kopfschmerzeinträgen.": "Creation and changes of headache entries.",
    "In der Datenbank angelegte Personenprofile.": "People profiles stored in the database.",
    "Globaler Katalog der verfügbaren Auslöser.": "Global catalogue of available triggers.",
    "Uhrzeiten, Schmerzseite und Begleitumstände, die im Notiztext erkannt und gegebenenfalls geprüft wurden.": "Times, side of pain, and circumstances recognised in the note text and reviewed where applicable.",
    "Die möglichen Auslöser, die bei den einzelnen Kopfschmerztagen ausgewählt wurden.": "The possible triggers selected for each headache day.",
    "Alle Auslöser, die im Eingabeformular ausgewählt werden können.": "All triggers that can be selected in the entry form.",
    }

    COLUMN_TRANSLATIONS = {
    "Datum": "Date",
    "Datum des Eintrags": "Entry date",
    "Stärke": "Intensity",
    "Dauer (h)": "Duration (h)",
    "Dauer (Std.)": "Duration (hours)",
    "Dauer (Stunden)": "Duration (hours)",
    "Auslöser": "Triggers",
    "Schmerzart": "Pain type",
    "Seite": "Side",
    "Seite (eingetragen)": "Side (entered)",
    "Seite (abgeleitet)": "Side (derived)",
    "Vorboten": "Aura",
    "Erbrechen": "Vomiting",
    "Übelkeit": "Nausea",
    "Lärmscheu": "Sensitivity to sound",
    "Lichtscheu": "Sensitivity to light",
    "Geruchsempfindlich": "Sensitivity to smell",
    "Andere Symptome": "Other symptoms",
    "Medikament": "Medication",
    "Medikamente": "Medications",
    "Medikation": "Medication",
    "Einnahmezeit": "Time taken",
    "Einnahme-ID": "Intake ID",
    "Dosis / Form": "Dose / form",
    "Wirkung": "Effect",
    "Notizen": "Notes",
    "Quelle": "Source",
    "Ursprünglicher KI-Eingabetext": "Original AI input text",
    "KI-Anbieter": "AI provider",
    "KI-Modell": "AI model",
    "KI-Promptversion": "AI prompt version",
    "KI-Entwurf geprüft am": "AI draft reviewed at",
    "Quellzeile": "Source row",
    "Quellfingerabdruck": "Source fingerprint",
    "Erstellt": "Created",
    "Geändert": "Updated",
    "Beginn": "Onset",
    "Höhepunkt": "Peak",
    "Höhepunkt Beginn": "Peak start",
    "Höhepunkt Ende": "Peak end",
    "Ende": "End",
    "Endstatus": "End status",
    "Seitendetail": "Side detail",
    "Kontexte": "Contexts",
    "Automatisch erkannte Schmerzseite": "Automatically recognised side of pain",
    "Genauere Angabe zur Schmerzseite": "More detail about the side of pain",
    "Erkannte Begleitumstände": "Recognised circumstances",
    "Sicherheit der automatischen Erkennung": "Confidence of automatic recognition",
    "Art der automatischen Erkennung": "Type of automatic recognition",
    "Symptome": "Symptoms",
    "Maßnahmen": "Interventions",
    "Konfidenz": "Confidence",
    "Methode": "Method",
    "Manuell geprüft": "Manually reviewed",
    "Geprüft am": "Reviewed at",
    "Beschreibung": "Description",
    "Aktion": "Action",
    "Zeitpunkt": "Timestamp",
    "Ursprung": "Origin",
    "Vorher": "Before",
    "Nachher": "After",
    "Quelldatei": "Source file",
    "Tabellenblatt": "Worksheet",
    "Status": "Status",
    "Hinweise": "Issues",
    "Importiert am": "Imported at",
    "Vollständiger Quellpfad": "Full source path",
    "Rohdaten": "Raw data",
    "Inhaltshash": "Content hash",
    "Name": "Name",
    "Erfassungsbeginn": "Tracking start",
    "Aktiv": "Active",
    "Namensschlüssel": "Name key",
    "Bezeichnung": "Label",
    "Reihenfolge": "Order",
    "Monat": "Month",
    "Beobachtungstage": "Observation days",
    "Kopfschmerztage": "Headache days",
    "Je 30 Tage": "Per 30 days",
    "Ø Stärke": "Avg. intensity",
    "Ø Dauer": "Avg. duration",
    "Stunden": "Hours",
    "Kontext": "Context",
    "Tage": "Days",
    "Anteil": "Share",
    "Wochentag": "Weekday",
    "Beobachtet": "Observed",
    "Quote": "Rate",
    "Geholfen": "Helped",
    "Teilweise": "Partly",
    "Nicht geholfen": "Did not help",
    "Ø Ausgangsstärke": "Avg. initial intensity",
    "Phase": "Phase",
    "Einordnung": "Context",
    "Feld": "Field",
    "Vollständig": "Complete",
    "Gesamt": "Total",
    "Zeilen": "Rows",
    "Zeitlicher Ablauf": "Timeline",
    "Mögliche Einflussfaktoren": "Possible factors",
    "Beschwerden und Maßnahmen": "Symptoms and actions",
    "Andere Notizen": "Other notes",
    "Hinweis": "Issue",
    }

    MONTHS_DE = ("Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")
    MONTHS_EN = ("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")

    ERROR_TRANSLATIONS = {
    "Mindestens ein Auslöser ist erforderlich.": "At least one trigger is required.",
    "Der ausgewählte Eintrag wurde nicht gefunden.": "The selected entry was not found.",
    "Für den Eintrag ist keine Interpretation vorhanden.": "No interpretation is available for this entry.",
    "Bitte geben Sie einen Namen mit mindestens zwei Zeichen ein.": "Please enter a name with at least two characters.",
    "Der Name darf höchstens 160 Zeichen lang sein.": "The name may contain no more than 160 characters.",
    "Die ausgewählte Person wurde nicht gefunden.": "The selected person was not found.",
    "Eine Person mit diesem Namen ist bereits vorhanden.": "A person with this name already exists.",
    "Bitte geben Sie eine Bezeichnung mit mindestens zwei Zeichen ein.": "Please enter a label with at least two characters.",
    "Die Bezeichnung darf höchstens 160 Zeichen lang sein.": "The label may contain no more than 160 characters.",
    "Die Beschreibung darf höchstens 2.000 Zeichen lang sein.": "The description may contain no more than 2,000 characters.",
    "Ein Auslöser mit dieser Bezeichnung ist bereits vorhanden.": "A trigger with this label already exists.",
    "Der ausgewählte Datenbereich ist nicht verfügbar.": "The selected data area is not available.",
    "Für die KI-Auswertung ist kein Groq-API-Schlüssel konfiguriert.": "No Groq API key is configured for AI analysis.",
    "Bitte geben Sie zuerst eine Beschreibung der Kopfschmerzen ein.": "Enter a description of the headache first.",
    "Die KI-Auswertung konnte nicht abgeschlossen werden. Prüfen Sie den API-Schlüssel und die Internetverbindung.": "AI analysis could not be completed. Check the API key and internet connection.",
    "Die KI hat keinen auswertbaren Entwurf zurückgegeben.": "AI did not return a usable draft.",
    "Auslöser fehlt im Altbestand; als ND (nicht dokumentiert) übernommen.": "Trigger missing in legacy data; imported as ND (not documented).",
    }